language: python
python:
  - "2.7"
  - "3.4"
install:
- pip install coveralls
script: coverage run --source=. -m unittest discover -s fcap/tests/
notifications:
  email:
    recipients:
      - hieulq19@gmail.com
      - daibk115@gmail.com
    on_success: change
    on_failure: always
after_success:
- coveralls
