# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170401_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/avatar.png', upload_to='avatars'),
        ),
    ]
