# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectServiceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.IntegerField(choices=[(1, 'SWIFT'), (2, 'AMAZON_S3'), (3, 'CEPH')])),
                ('specifications', models.CharField(max_length=1023, verbose_name='specifications')),
                ('auth_info', models.CharField(max_length=1023, verbose_name='auth_info')),
                ('distance_info', models.CharField(blank=True, default='', max_length=1023, verbose_name='distance_info')),
            ],
            options={
                'db_table': 'cloud_service_info',
            },
        ),
        migrations.CreateModel(
            name='SystemCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('address_ip', models.CharField(max_length=255, verbose_name='ip')),
                ('address_port', models.CharField(max_length=255, verbose_name='port')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'SHUTOFF'), (3, 'DISCONNECTED'), (4, 'CLOUD_SERVICE_DISCONNECTED')], default=1)),
                ('service_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_cluster', to='admin.ObjectServiceInfo')),
            ],
            options={
                'db_table': 'system_cluster',
            },
        ),
    ]
